name: Update GitHub Secret

on:
  workflow_dispatch: # 允许手动触发


jobs:
  update-secret:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Authenticate with GitHub CLI
        env:
          ORG: cloudbtjp
        run: |
          echo ${{ steps.generate_token.outputs.token }} | gh auth login --with-token

      - name: Update GitHub Secret
        run: |
          NEW_SECRET_VALUE="This is the new secret value lide"
          gh secret set TESTGITHUBCLI --body="NEW_SECRET_VALUE" --env=dev
