name: "Updating jiraSM API Token saved to Azure KV"

on:
  workflow_dispatch:
    inputs:
      JIRAUSER:
        type: string
      # APITOKEN:
      #   type: string

jobs:
  update-jiraSM-ApiToken-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update jiraSM ApiToken
        run: |
          az keyvault secret set \
            --name github-action \
            --value "${{ inputs.JIRAUSER }}" \
            --vault-name kv-github-ap
