name: "Updating jiraSM API Token saved to Azure KV"

on:
  workflow_dispatch:
    inputs:
      JIRAUSER:
        type: string
      # APITOKEN:
      #   type: string

jobs:
  update-jiraSM-ApiToken-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          auth-type: service-principal

      - name: show jiraSM ApiToken
        run: |
          az keyvault secret show \
            --name test-githubAction \
            --vault-name kv-work-githubAction

          az keyvault secret set \
            --name test-githubAction \
            --value "${{ inputs.JIRAUSER }}" \
            --vault-name kv-work-githubAction
  
  update-jiraSM-ApiToken-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          auth-type: service-principal

      - name: update jiraSM ApiToken
        run: |
          az keyvault secret set \
            --name test-githubAction \
            --value "${{ inputs.JIRAUSER }}" \
            --vault-name kv-work-githubAction
